api/urls.py
from django.urls import path
from api import views

urlpatterns = [
    path('', views.NoteList.as_view()),
    path('<int:pk>/', views.NoteDetail.as_view()),

    path('faq/', views.FaqList.as_view()),
    path('faq/<int:pk>/', views.FaqDetail.as_view()),
]

notes_app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.urls import include, path

from  api import views

urlpatterns = [
    path('',  include('api.urls')),
    path('admin/', admin.site.urls),
    path('api/', include('api.urls')), 
    path('faq/', include('api.urls')), 
    path('polls/', include('polls.urls')),
    path('home/',  include('yellowpage.urls')),
   
    
    
     # add this line
]

polls/urls.py
from django.urls import path
from . import views

urlpatterns = [
    # ex: /polls/
    path('', views.index, name='index'),
    # ex: /polls/5/
    path('<int:question_id>/', views.detail, name='detail'),
    # ex: /polls/5/results/
    path('<int:question_id>/results/', views.results, name='results'),
    # ex: /polls/5/vote/
    path('<int:question_id>/vote/', views.vote, name='vote'),
]

yellowpage/urls.py
from django.urls import path
from django.conf.urls import url

from django.views.generic import TemplateView
from . import views

# direct to view home conents
urlpatterns = [
    path('', views.home, name='yellowpage-home'),
    path('connection/', views.login, name='yellowpage-login'),

  
]

api/models.py
from django.db import models
from django.utils import timezone

class Note(models.Model):
    title = models.CharField(max_length=100)
    text = models.TextField()
    author = models.CharField(max_length=100, default='joel wembo')
    username = models.CharField(max_length=100, default='joelwembo')
    link = models.CharField(max_length=100, default='https:google.com')
    date_field = models.DateField(default=timezone.now, max_length=150)

    def __str__(self):
        return self.title




    

polls/models.py
from django.db import models
import datetime
from django.utils import timezone



class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')
    def __str__(self):
        return self.question_text

    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    def __str__(self):
        return self.choice_text

quickstart/models.py
from django.db import models

# Create your models here.

yellowpage/models.py
from django.db import models

# Create your models here.

yellowpage/forms.py
#-*- coding: utf-8 -*-
from django import forms

class LoginForm(forms.Form):
   user = forms.CharField(max_length = 100)
   password = forms.CharField(widget = forms.PasswordInput())

   

api/views.py
from rest_framework import generics
from .models import Note
from .serializers import NoteSerializer

from .Faq import Faq
from .serializers import FaqSerializer


class NoteList(generics.ListCreateAPIView):
    queryset = Note.objects.all()
    serializer_class = NoteSerializer

class NoteDetail(generics.RetrieveUpdateDestroyAPIView):
    queryset = Note.objects.all()
    serializer_class = NoteSerializer

class FaqList(generics.ListCreateAPIView):
    queryset = Faq.objects.all()
    serializer_class = FaqSerializer

class FaqDetail(generics.RetrieveUpdateDestroyAPIView):
    queryset = Faq.objects.all()
    serializer_class = FaqSerializer    

polls/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponse
from django.template import loader

from .models import Question

# Create your views here.]


def index(request):
    latest_question_list = Question.objects.order_by('-pub_date')[:5]
    template = loader.get_template('polls/index.html')
    context = {
        'latest_question_list': latest_question_list,
    }
    return HttpResponse(template.render(context, request))

def detail(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'polls/detail.html', {'question': question})

def results(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'polls/results.html', {'question': question})

def vote(request, question_id):
    return HttpResponse("You're voting on question %s." % question_id)



quickstart/views.py
from django.shortcuts import render

# Create your views here.

yellowpage/views.py
#-*- coding: utf-8 -*-

from django.shortcuts import render
from django.http import HttpResponse
from .forms import LoginForm

# Create your views here.

def home(request):
    #return HttpResponse('<h1>Blog Home</h1>')
   
    return render(request, 'yellowpage/home.html')

def login(request):
    username = "not logged in"

   
    if request.method == "POST":
          #Get the posted form
      MyLoginForm = LoginForm(request.POST)
      
      if MyLoginForm.is_valid():
         username = MyLoginForm.cleaned_data['username']
    else:
        MyLoginForm = LoginForm()
		
    return render(request, 'yellowpage/loggedin.html', {"username" : username})    

polls/templates/polls/details.html
<h1>{{ question.question_text }}</h1>
<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }}</li>
{% endfor %}
</ul>

<p>
    Details
</p>

polls/templates/polls/index.html
{% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
    <li><a href="{% url 'detail' question.id %}">{{ question.question_text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available...</p>
{% endif %}

yellowpage/templates/yellowpage/home.html
<!doctype html>
<html lang="en">
  <head>
    
    {% load static %}
    <link rel="stylesheet" href="{% static 'yellowpage/starter-template.css' %}"/>
    <!-- Bootstrap core CSS -->
    {% load static %}
    <link href="{% static 'yellowpage/bootstrap.css' %}" rel="stylesheet"  />

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.83.1">
    <title>Home | Rest Frameworks</title>

    

    



    
    <!-- Custom styles for this template -->
 
  </head>
  <body>
    
<div class="col-lg-8 mx-auto p-3 py-md-5">
  <header class="d-flex align-items-center pb-3 mb-5 border-bottom">
    <a href="/" class="d-flex align-items-center text-dark text-decoration-none">
      <svg xmlns="http://www.w3.org/2000/svg" width="40" height="32" class="me-2" viewBox="0 0 118 94" role="img"><title>Bootstrap</title><path fill-rule="evenodd" clip-rule="evenodd" d="M24.509 0c-6.733 0-11.715 5.893-11.492 12.284.214 6.14-.064 14.092-2.066 20.577C8.943 39.365 5.547 43.485 0 44.014v5.972c5.547.529 8.943 4.649 10.951 11.153 2.002 6.485 2.28 14.437 2.066 20.577C12.794 88.106 17.776 94 24.51 94H93.5c6.733 0 11.714-5.893 11.491-12.284-.214-6.14.064-14.092 2.066-20.577 2.009-6.504 5.396-10.624 10.943-11.153v-5.972c-5.547-.529-8.934-4.649-10.943-11.153-2.002-6.484-2.28-14.437-2.066-20.577C105.214 5.894 100.233 0 93.5 0H24.508zM80 57.863C80 66.663 73.436 72 62.543 72H44a2 2 0 01-2-2V24a2 2 0 012-2h18.437c9.083 0 15.044 4.92 15.044 12.474 0 5.302-4.01 10.049-9.119 10.88v.277C75.317 46.394 80 51.21 80 57.863zM60.521 28.34H49.948v14.934h8.905c6.884 0 10.68-2.772 10.68-7.727 0-4.643-3.264-7.207-9.012-7.207zM49.948 49.2v16.458H60.91c7.167 0 10.964-2.876 10.964-8.281 0-5.406-3.903-8.178-11.425-8.178H49.948z" fill="currentColor"></path></svg>
      <span class="fs-4">Starter template</span>
    </a>
  </header>

  <main>
    <h1>Get started with Bootstrap</h1>
    <p class="fs-5 col-md-8">Quickly and easily get started with Bootstrap's compiled, production-ready files with this barebones example featuring some basic HTML and helpful links. Download all our examples to get started.</p>

    <div class="mb-5">
      <a href="../examples/" class="btn btn-primary btn-lg px-4">Download examples</a>
    </div>

    <hr class="col-3 col-md-2 mb-5">

    <div class="row g-5">
      <div class="col-md-6">
        <h2>Starter projects</h2>
        <p>Ready to beyond the starter template? Check out these open source projects that you can quickly duplicate to a new GitHub repository.</p>
        <ul class="icon-list">
          <li><a href="https://github.com/twbs/bootstrap-npm-starter" rel="noopener" target="_blank">Bootstrap npm starter</a></li>
          <li class="text-muted">Bootstrap Parcel starter (coming soon!)</li>
        </ul>
      </div>

      <div class="col-md-6">
        <h2>Guides</h2>
        <p>Read more detailed instructions and documentation on using or contributing to Bootstrap.</p>
        <ul class="icon-list">
          <li><a href="../getting-started/introduction/">Bootstrap quick start guide</a></li>
          <li><a href="../getting-started/webpack/">Bootstrap Webpack guide</a></li>
          <li><a href="../getting-started/parcel/">Bootstrap Parcel guide</a></li>
          <li><a href="../getting-started/build-tools/">Contributing to Bootstrap</a></li>
        </ul>
      </div>
    </div>
  </main>
  <footer class="pt-5 my-5 text-muted border-top">
    Created by the Bootstrap team &middot; &copy; 2021
  </footer>
</div>


    

      
  </body>
</html>

yellowpage/templates/yellowpage/loggedin.html
<html>
   
   <body>
      You are : <strong>{{username}}</strong>
   </body>
   
</html>

yellowpage/templates/yellowpage/login.html
<html>
    <body>
       
       <form name = "form" action = "{% url "yellowpage.views.login" %}" 
          method = "POST" >{% csrf_token %}
          
          <div style = "max-width:470px;">
             <center> 
                <input type = "text" style = "margin-left:20%;" 
                   placeholder = "Identifiant" name = "username" />
             </center>
          </div>
             
          <br>
          
          <div style = "max-width:470px;">
             <center>
                <input type = "password" style = "margin-left:20%;" 
                   placeholder = "password" name = "password" />
             </center>
          </div>
             
          <br>
          
          <div style = "max-width:470px;">
             <center> 
             
                <button style = "border:0px; background-color:#4285F4; margin-top:8%;
                   height:35px; width:80%;margin-left:19%;" type = "submit" 
                   value = "Login" >
                   <strong>Login</strong>
                </button>
                
             </center>
          </div>
          
       </form>
       
    </body>
 </html>